config/routes.rb
Rails.application.routes.draw do
  root 'profiles#home'

  get 'profiles/:id/index', controller: 'profiles', action: 'index', as: 'profiles/index'
  get 'profiles/users_search'

  get 'followers/:id/follow', controller: 'followers', action: 'follow', as: 'followers/follow'
  get 'followers/:id/unfollow', controller: 'followers', action: 'unfollow', as: 'followers/unfollow'

  devise_for :users
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follower.rb
class Follower < ApplicationRecord
  belongs_to :user, foreign_key: :user_id
  belongs_to :follower_user, class_name: 'User', foreign_key: :follower_user_id
  has_many :posts, through: :follower_user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :followers, foreign_key: :follower_user_id, dependent: :destroy
  has_many :followed,  class_name: 'Follower', foreign_key: :user_id

  def followed_for? user
    self.followers.map{|f| f.user}.include? user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  ensure_security_headers # See more: https://github.com/twitter/secureheaders

end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  before_action :authenticate_user!

  def follow
    follower = Follower.new(user_id: current_user.id, follower_user_id: params[:id])
    respond_to do |format|
      if follower.save
        CustomMailer.follow_notification(current_user, params[:id]).deliver_now
        format.html { redirect_to profiles_index_path(params[:id]), notice: 'Você está conectado com este usuário!' }
      else
        format.html { redirect_to profiles_index_path(params[:id])}
      end
    end
  end

  def unfollow
    user = User.find(params[:id])
    follower = user.followers.where(user_id: current_user.id).first
    respond_to do |format|
      if follower.destroy
        format.html { redirect_to profiles_index_path(user.id), notice: 'Você deixou de seguir este usuário!' }
      else
        format.html { redirect_to profiles_index_path(user.id) }
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :require_permission, only: [:edit, :update]

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to profiles_index_path(current_user.id), notice: 'Post criado com sucesso.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to profiles_index_path(current_user.id), notice: 'Post atualizado com sucesso.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
    def require_permission
      if current_user != Post.find(params[:id]).user
        flash[:alert] = "Você não tem permissão, para esta ação!"
        redirect_to root_path
      end
    end

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:comment, :user_id)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def home
    if current_user && current_user.followers
      @posts = current_user.followed.map{|f| f.posts.includes(:user)}.flatten
    end
  end

  def index
    @user = params[:id].present? ? User.find(params[:id]) : current_user
    @posts = @user.posts.order(created_at: :desc)
  end

  def users_search
    @users = User.where("email LIKE '%#{params[:email]}%'")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert"
      a class="close" onclick="$('.alert').hide()" x
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/application/_navigation.html.slim
div class="container"
  div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"
    ul class="nav navbar-nav"
      li
        = link_to "Thinking What", root_path
      - if user_signed_in?
        li
          = link_to "Meu Perfil", profiles_index_path(current_user.id)
        li
          = link_to('Editar', edit_user_registration_path)
        li
          = link_to('Sair', destroy_user_session_path, :method=>'delete')
      - else
        li
          = link_to('Entrar', new_user_session_path)
        li
          = link_to('Cadastrar', new_user_registration_path)

app/views/layouts/_users_search.html.slim
div class="well row"
  = form_tag profiles_users_search_path(:email), method: :get do
    div class="form-group"
      div class="col-md-10"
        = text_field_tag :email, params[:email], class: "form-control"
      div class="col-md-2"
        = submit_tag "Busca", class: 'btn btn-primary'
hr/

app/views/layouts/application.html.slim
doctype 5
html lang="pt"
  head
    meta charset="utf-8"
    meta name="keywords" content=""
    meta name="description" content=""

    title
      = page_title(app_name: 'Pensando em Que?')

    link href="/favicon.ico" rel=("shortcut icon")

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    /![if lt IE 9]
      script src="http://html5shim.googlecode.com/svn/trunk/html5.js"

  body
    nav class="navbar navbar-inverse navbar-fixed-top" role="navigation"
      = render 'navigation'
    div class="container"
      div class="row"
        div class="col-lg-12"
          = render 'flash_messages'
          = yield

app/views/posts/_form.html.slim
div class="well"
  = form_for(post) do |f|
    - if post.errors.any?
      div id="error_explanation"
        h2 = pluralize(post.errors.count, "Erro(s)")
        ul
          - post.errors.full_messages.each do |message|
            li
              = message
    div class="form-group"
      div class="field"
        = f.label "No que você está pensando?"
        = f.text_area :comment, class: "form-control"
    div class="form-group-sm"
      div class="actions"
        = f.submit 'Salvar', class: 'btn btn-primary'
        = link_to "Voltar", :back, class: 'right btn btn-default'

app/views/posts/edit.html.slim
h1 Editar Post

= render 'form', post: @post

app/views/posts/new.html.slim
h1 Novo Post

= render 'form', post: @post

app/views/profiles/home.html.slim
= render 'layouts/users_search'

- if user_signed_in?
  - if @posts.present?
    - @posts.each do |post|
      div class="well row"
        div class='right'
          span class="small"
            = "#{post.user.email} - #{I18n.l post.created_at.to_date}"
        div class="post-comment"
          = post.comment
  - else
    div class="well row"
      p Não existe nenhum post, para mostrar!
- else
  h1 Bem Vindo ao Pensando em Que?

  div
    p Para compartilhar seus pensamentos, você deve se cadastrar ou logar!
    = link_to('Cadastrar', new_user_registration_path)

app/views/profiles/index.html.slim
= render 'layouts/users_search'

h2 = "Perfil #{@user.email}"

- if user_signed_in?
  div
    - if @user.id != current_user.id
      span
        - if @user.followed_for? current_user
          = link_to('Deixar de Seguir', followers_unfollow_path(@user.id), class: 'btn btn-default', data: { disable_with: "Aguarde..."})
        - else
          = link_to('Seguir', followers_follow_path(@user.id), class: 'btn btn-primary', data: { disable_with: "Aguarde..."})
  div
    = link_to('Novo Post', new_post_path, class: 'btn btn-primary') if @user.id == current_user.id

hr/

- if @posts.present?
  - @posts.each do |post|
    div class="well row"
      div class='right'
        span class="small"
          = "#{post.user.email} - #{I18n.l post.created_at.to_date}"
      div class="post-comment"
        = post.comment
      - if user_signed_in?
        div class='right'
          = link_to 'Editar', edit_post_path(post.id), class: 'btn btn-default' if @user.id == current_user.id
- else
  div class="well row"
    p Não existe nenhum post, para mostrar!

app/views/profiles/users_search.html.slim
= render 'layouts/users_search'

div class="col-md-12"
  h3 Usuários Encontrados
  div class="table table-hover"
    - if @users.present?
      - @users.each do |user|
        p class="well"
          = link_to(user.email, profiles_index_path(user.id))
    - else
      p class='well' Nenhum perfil encontrado!